export const SHOP_GET_ITEMS_SUCCESS = 'SHOP__GET_ITEMS@@SUCCESS';
export const SHOP_GET_ITEMS_FAILED = 'SHOP__GET_ITEMS@@FAILED';

export const MY_THINGS_GET = 'MY__THINGS@@GET';
export const WEB3_GET_INSTANCE = "WEB3@@GET_INSTANCE";
export const GET_DEVERY_PRODUCT_LIST = "DEVERY@@GET_PRODUCT_LIST";